<a href="https://colab.research.google.com/github/saraspotey2-debug/MINI_PROJECT/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/raw data students.csv")
df

   Student_ID  Department  Attendance   GPA Living  Gender
0    Student1        AIML          85   8.2   Home    Male
1    Student2    Robotics          78   7.5     PG  Female
2    Student3  Mechanical          65   6.8   Home    Male
3    Student4        ENTC          90   9.1     PG  Female
4    Student5       Civil          72   7.0   Home    Male
5    Student6          CS          88   8.9     PG  Female
6    Student7        AIML          60   6.5   Home  Female
7    Student8    Robotics          82   8.0     PG    Male
8    Student9  Mechanical          75   7.2   Home    Male
9   Student10        ENTC          91   NaN     PG  Female
10  Student11       Civil          68   6.9   Home  Female
11  Student12          CS          87   8.7     PG    Male
12  Student13        AIML          77   7.8   Home    Male
13  Student14    Robotics          83   8.4     PG  Female
14  Student15  Mechanical          69   6.7   Home    Male
15  Student16        ENTC          92   9.5     PG  Female
16  Student17       Civil          74   NaN   Home  Female
17  Student18          CS          89   9.0     PG    Male
18  Student19        AIML          66   6.6   Home    Male
19  Student20    Robotics          80   7.9     PG  Female
20  Student21  Mechanical          71   7.0   Home    Male
21  Student22        ENTC          93   9.6     PG  Female
22  Student23       Civil          76   7.3   Home  Female
23  Student24          CS          86   8.8     PG    Male
24  Student25        AIML          64   6.4   Home  Female
25  Student26    Robotics          79   7.7     PG    Male
26  Student27  Mechanical          73   7.2   Home    Male
27  Student28        ENTC          94   9.7     PG  Female
28  Student29       Civil          67   6.8   Home  Female
29  Student30          CS          85   8.5     PG    Male
30  Student31        AIML          81   8.1   Home    Male
31  Student32    Robotics          84   8.3     PG  Female
32  Student33  Mechanical          70   7.0   Home    Male
33  Student34        ENTC          95   9.8     PG  Female
34  Student35       Civil          78   7.6   Home  Female
35  Student36          CS          90   9.2     PG    Male
36  Student37        AIML          62   6.3   Home    Male
37  Student38    Robotics          86   8.6     PG  Female
38  Student39  Mechanical          74   7.4   Home    Male
39  Student40        ENTC          96   9.9     PG  Female
40  Student41       Civil          69   6.9   Home  Female
41  Student42          CS          91   9.3     PG    Male
42  Student43        AIML          83   8.2   Home  Female
43  Student44    Robotics          88   8.9     PG    Male
44  Student45  Mechanical          72   7.1   Home    Male
45  Student46        ENTC          97  10.0     PG  Female
46  Student47       Civil          75   7.5   Home  Female
47  Student48          CS          92   9.4     PG    Male
48  Student49        AIML          68   6.8   Home    Male
49  Student50    Robotics          87   8.7     PG  Female

Coding Part

Data Analysis

In [ ]:
df.size

300

In [ ]:
df.shape

(50, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  50 non-null     object
 1   Department  50 non-null     object
 2   Attendance  50 non-null     int64
 3   GPA         48 non-null     float64
 4   Living      50 non-null     object
 5   Gender      50 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 2.5+ KB

In [ ]:
df.head()

  Student_ID  Department  Attendance  GPA Living  Gender
0   Student1        AIML          85  8.2   Home    Male
1   Student2    Robotics          78  7.5     PG  Female
2   Student3  Mechanical          65  6.8   Home    Male
3   Student4        ENTC          90  9.1     PG  Female
4   Student5       Civil          72  7.0   Home    Male

In [ ]:
df.tail()

   Student_ID Department  Attendance   GPA Living  Gender
45  Student46       ENTC          97  10.0     PG  Female
46  Student47      Civil          75   7.5   Home  Female
47  Student48         CS          92   9.4     PG    Male
48  Student49       AIML          68   6.8   Home    Male
49  Student50   Robotics          87   8.7     PG  Female

In [ ]:
df.sample(5)

   Student_ID  Department  Attendance  GPA Living  Gender
21  Student22        ENTC          93  9.6     PG  Female
29  Student30          CS          85  8.5     PG    Male
14  Student15  Mechanical          69  6.7   Home    Male
13  Student14    Robotics          83  8.4     PG  Female
23  Student24          CS          86  8.8     PG    Male

In [ ]:
df.columns

Index(['Student_ID', 'Department', 'Attendance', 'GPA', 'Living', 'Gender'], dtype='object')

In [ ]:
df.isnull().sum()

Student_ID    0
Department    0
Attendance    0
GPA           2
Living        0
Gender        0
dtype: int64

In [ ]:
df.describe()

       Attendance        GPA
count   50.000000  48.000000
mean    79.940000   8.014583
std     10.047662   1.080384
min     60.000000   6.300000
25%     72.000000   7.000000
50%     80.500000   7.950000
75%     88.000000   8.900000
max     97.000000  10.000000

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
df.nunique()

Student_ID    50
Department     6
Attendance    36
GPA           38
Living         2
Gender         2
dtype: int64

Categorial Data Analysis

In [ ]:
#display is used to print the data in tabular form
print(df['Department'].value_counts())

Department
AIML          9
Robotics      9
Mechanical    8
ENTC          8
Civil         8
CS            8
Name: count, dtype: int64

In [ ]:
print(df['Living'].value_counts())

Living
Home    25
PG      25
Name: count, dtype: int64

In [ ]:
print(df['Gender'].value_counts())

Gender
Male      25
Female    25
Name: count, dtype: int64

In [ ]:
#Percentage Distribution of Department
print("Department Percentage")
print(df['Department'].value_counts(normalize=True)*100)

Department Percentage
Department
AIML          18.0
Robotics      18.0
Mechanical    16.0
ENTC          16.0
Civil         16.0
CS            16.0
Name: proportion, dtype: float64

In [ ]:
#Percentage distribution of Living
print("Living Percentage")
print(df['Living'].value_counts(normalize=True)*100)

Living Percentage
Living
Home    50.0
PG      50.0
Name: proportion, dtype: float64

In [ ]:
#Percentage Distribution of Gender
print("Gender Percentage")
print(df['Gender'].value_counts(normalize=True)*100)

Gender Percentage
Gender
Male      50.0
Female    50.0
Name: proportion, dtype: float64

In [ ]:
#Department vs Gender Analysis
print(pd.crosstab(df['Department'],df['Gender']))

Gender      Female  Male
Department
AIML             3     6
CS               1     7
Civil            7     1
ENTC             8     0
Mechanical       0     8
Robotics         6     3

In [ ]:
#Department  vs  Living Analysis
print(pd.crosstab(df['Department'],df['Living']))

Living      Home  PG
Department
AIML           9   0
CS             0   8
Civil          8   0
ENTC           0   8
Mechanical     8   0
Robotics       0   9

In [ ]:
#Gender  vs  Living in percentage
print(pd.crosstab(df['Gender'],df['Living']))

Living  Home  PG
Gender
Female    10  15
Male      15  10

In [ ]:
#Department vs  Living in percentage
print(pd.crosstab(df['Department'],df['Gender'],normalize='index')*100)

Gender          Female        Male
Department
AIML         33.333333   66.666667
CS           12.500000   87.500000
Civil        87.500000   12.500000
ENTC        100.000000    0.000000
Mechanical    0.000000  100.000000
Robotics     66.666667   33.333333

In [ ]:
#Department vs  Living in percentage
print(pd.crosstab(df['Department'],df['Living'],normalize='index')*100)

Living       Home     PG
Department
AIML        100.0    0.0
CS            0.0  100.0
Civil       100.0    0.0
ENTC          0.0  100.0
Mechanical  100.0    0.0
Robotics      0.0  100.0

In [ ]:
#Grouping Data
print(df.groupby('Department')['Gender'].value_counts())

Department  Gender
AIML        Male      6
            Female    3
CS          Male      7
            Female    1
Civil       Female    7
            Male      1
ENTC        Female    8
Mechanical  Male      8
Robotics    Female    6
            Male      3
Name: count, dtype: int64

In [ ]:
print(df['Department'].unique())

['AIML' 'Robotics' 'Mechanical' 'ENTC' 'Civil' 'CS']

In [ ]:
# Filtering Data
Student_CS=df[df['Department']=='CS']
print(Student_CS)

   Student_ID Department  Attendance  GPA Living  Gender
5    Student6         CS          88  8.9     PG  Female
11  Student12         CS          87  8.7     PG    Male
17  Student18         CS          89  9.0     PG    Male
23  Student24         CS          86  8.8     PG    Male
29  Student30         CS          85  8.5     PG    Male
35  Student36         CS          90  9.2     PG    Male
41  Student42         CS          91  9.3     PG    Male
47  Student48         CS          92  9.4     PG    Male

In [ ]:
#Sorting Data
sorted_df=df.sort_values(by='Department')
print(sorted_df)

   Student_ID  Department  Attendance   GPA Living  Gender
0    Student1        AIML          85   8.2   Home    Male
42  Student43        AIML          83   8.2   Home  Female
36  Student37        AIML          62   6.3   Home    Male
30  Student31        AIML          81   8.1   Home    Male
48  Student49        AIML          68   6.8   Home    Male
18  Student19        AIML          66   6.6   Home    Male
12  Student13        AIML          77   7.8   Home    Male
24  Student25        AIML          64   6.4   Home  Female
6    Student7        AIML          60   6.5   Home  Female
35  Student36          CS          90   9.2     PG    Male
29  Student30          CS          85   8.5     PG    Male
11  Student12          CS          87   8.7     PG    Male
47  Student48          CS          92   9.4     PG    Male
41  Student42          CS          91   9.3     PG    Male
23  Student24          CS          86   8.8     PG    Male
17  Student18          CS          89   9.0     PG    Male
5    Student6          CS          88   8.9     PG  Female
40  Student41       Civil          69   6.9   Home  Female
4    Student5       Civil          72   7.0   Home    Male
22  Student23       Civil          76   7.3   Home  Female
34  Student35       Civil          78   7.6   Home  Female
28  Student29       Civil          67   6.8   Home  Female
16  Student17       Civil          74   NaN   Home  Female
46  Student47       Civil          75   7.5   Home  Female
10  Student11       Civil          68   6.9   Home  Female
45  Student46        ENTC          97  10.0     PG  Female
15  Student16        ENTC          92   9.5     PG  Female
27  Student28        ENTC          94   9.7     PG  Female
39  Student40        ENTC          96   9.9     PG  Female
9   Student10        ENTC          91   NaN     PG  Female
3    Student4        ENTC          90   9.1     PG  Female
33  Student34        ENTC          95   9.8     PG  Female
21  Student22        ENTC          93   9.6     PG  Female
38  Student39  Mechanical          74   7.4   Home    Male
2    Student3  Mechanical          65   6.8   Home    Male
44  Student45  Mechanical          72   7.1   Home    Male
8    Student9  Mechanical          75   7.2   Home    Male
26  Student27  Mechanical          73   7.2   Home    Male
20  Student21  Mechanical          71   7.0   Home    Male
14  Student15  Mechanical          69   6.7   Home    Male
32  Student33  Mechanical          70   7.0   Home    Male
37  Student38    Robotics          86   8.6     PG  Female
31  Student32    Robotics          84   8.3     PG  Female
7    Student8    Robotics          82   8.0     PG    Male
25  Student26    Robotics          79   7.7     PG    Male
1    Student2    Robotics          78   7.5     PG  Female
43  Student44    Robotics          88   8.9     PG    Male
19  Student20    Robotics          80   7.9     PG  Female
13  Student14    Robotics          83   8.4     PG  Female
49  Student50    Robotics          87   8.7     PG  Female

In [ ]:
Dealing with missing values

In [ ]:
#Boolean function
df.isna ()

    Student_ID  Department  Attendance    GPA  Living  Gender
0        False       False       False  False   False   False
1        False       False       False  False   False   False
2        False       False       False  False   False   False
3        False       False       False  False   False   False
4        False       False       False  False   False   False
5        False       False       False  False   False   False
6        False       False       False  False   False   False
7        False       False       False  False   False   False
8        False       False       False  False   False   False
9        False       False       False   True   False   False
10       False       False       False  False   False   False
11       False       False       False  False   False   False
12       False       False       False  False   False   False
13       False       False       False  False   False   False
14       False       False       False  False   False   False
15       False       False       False  False   False   False
16       False       False       False   True   False   False
17       False       False       False  False   False   False
18       False       False       False  False   False   False
19       False       False       False  False   False   False
20       False       False       False  False   False   False
21       False       False       False  False   False   False
22       False       False       False  False   False   False
23       False       False       False  False   False   False
24       False       False       False  False   False   False
25       False       False       False  False   False   False
26       False       False       False  False   False   False
27       False       False       False  False   False   False
28       False       False       False  False   False   False
29       False       False       False  False   False   False
30       False       False       False  False   False   False
31       False       False       False  False   False   False
32       False       False       False  False   False   False
33       False       False       False  False   False   False
34       False       False       False  False   False   False
35       False       False       False  False   False   False
36       False       False       False  False   False   False
37       False       False       False  False   False   False
38       False       False       False  False   False   False
39       False       False       False  False   False   False
40       False       False       False  False   False   False
41       False       False       False  False   False   False
42       False       False       False  False   False   False
43       False       False       False  False   False   False
44       False       False       False  False   False   False
45       False       False       False  False   False   False
46       False       False       False  False   False   False
47       False       False       False  False   False   False
48       False       False       False  False   False   False
49       False       False       False  False   False   False

In [ ]:
df.notna()

    Student_ID  Department  Attendance    GPA  Living  Gender
0         True        True        True   True    True    True
1         True        True        True   True    True    True
2         True        True        True   True    True    True
3         True        True        True   True    True    True
4         True        True        True   True    True    True
5         True        True        True   True    True    True
6         True        True        True   True    True    True
7         True        True        True   True    True    True
8         True        True        True   True    True    True
9         True        True        True  False    True    True
10        True        True        True   True    True    True
11        True        True        True   True    True    True
12        True        True        True   True    True    True
13        True        True        True   True    True    True
14        True        True        True   True    True    True
15        True        True        True   True    True    True
16        True        True        True  False    True    True
17        True        True        True   True    True    True
18        True        True        True   True    True    True
19        True        True        True   True    True    True
20        True        True        True   True    True    True
21        True        True        True   True    True    True
22        True        True        True   True    True    True
23        True        True        True   True    True    True
24        True        True        True   True    True    True
25        True        True        True   True    True    True
26        True        True        True   True    True    True
27        True        True        True   True    True    True
28        True        True        True   True    True    True
29        True        True        True   True    True    True
30        True        True        True   True    True    True
31        True        True        True   True    True    True
32        True        True        True   True    True    True
33        True        True        True   True    True    True
34        True        True        True   True    True    True
35        True        True        True   True    True    True
36        True        True        True   True    True    True
37        True        True        True   True    True    True
38        True        True        True   True    True    True
39        True        True        True   True    True    True
40        True        True        True   True    True    True
41        True        True        True   True    True    True
42        True        True        True   True    True    True
43        True        True        True   True    True    True
44        True        True        True   True    True    True
45        True        True        True   True    True    True
46        True        True        True   True    True    True
47        True        True        True   True    True    True
48        True        True        True   True    True    True
49        True        True        True   True    True    True

In [ ]:
df.isnull()

    Student_ID  Department  Attendance    GPA  Living  Gender
0        False       False       False  False   False   False
1        False       False       False  False   False   False
2        False       False       False  False   False   False
3        False       False       False  False   False   False
4        False       False       False  False   False   False
5        False       False       False  False   False   False
6        False       False       False  False   False   False
7        False       False       False  False   False   False
8        False       False       False  False   False   False
9        False       False       False   True   False   False
10       False       False       False  False   False   False
11       False       False       False  False   False   False
12       False       False       False  False   False   False
13       False       False       False  False   False   False
14       False       False       False  False   False   False
15       False       False       False  False   False   False
16       False       False       False   True   False   False
17       False       False       False  False   False   False
18       False       False       False  False   False   False
19       False       False       False  False   False   False
20       False       False       False  False   False   False
21       False       False       False  False   False   False
22       False       False       False  False   False   False
23       False       False       False  False   False   False
24       False       False       False  False   False   False
25       False       False       False  False   False   False
26       False       False       False  False   False   False
27       False       False       False  False   False   False
28       False       False       False  False   False   False
29       False       False       False  False   False   False
30       False       False       False  False   False   False
31       False       False       False  False   False   False
32       False       False       False  False   False   False
33       False       False       False  False   False   False
34       False       False       False  False   False   False
35       False       False       False  False   False   False
36       False       False       False  False   False   False
37       False       False       False  False   False   False
38       False       False       False  False   False   False
39       False       False       False  False   False   False
40       False       False       False  False   False   False
41       False       False       False  False   False   False
42       False       False       False  False   False   False
43       False       False       False  False   False   False
44       False       False       False  False   False   False
45       False       False       False  False   False   False
46       False       False       False  False   False   False
47       False       False       False  False   False   False
48       False       False       False  False   False   False
49       False       False       False  False   False   False

In [ ]:
df.isna().sum()

Student_ID    0
Department    0
Attendance    0
GPA           2
Living        0
Gender        0
dtype: int64

In [ ]:
#rowwise na values
df.isna().sum(axis=1)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     1
10    0
11    0
12    0
13    0
14    0
15    0
16    1
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
dtype: int64

In [ ]:
#NaN rows are dropped
df.dropna ()

   Student_ID  Department  Attendance   GPA Living  Gender
0    Student1        AIML          85   8.2   Home    Male
1    Student2    Robotics          78   7.5     PG  Female
2    Student3  Mechanical          65   6.8   Home    Male
3    Student4        ENTC          90   9.1     PG  Female
4    Student5       Civil          72   7.0   Home    Male
5    Student6          CS          88   8.9     PG  Female
6    Student7        AIML          60   6.5   Home  Female
7    Student8    Robotics          82   8.0     PG    Male
8    Student9  Mechanical          75   7.2   Home    Male
10  Student11       Civil          68   6.9   Home  Female
11  Student12          CS          87   8.7     PG    Male
12  Student13        AIML          77   7.8   Home    Male
13  Student14    Robotics          83   8.4     PG  Female
14  Student15  Mechanical          69   6.7   Home    Male
15  Student16        ENTC          92   9.5     PG  Female
17  Student18          CS          89   9.0     PG    Male
18  Student19        AIML          66   6.6   Home    Male
19  Student20    Robotics          80   7.9     PG  Female
20  Student21  Mechanical          71   7.0   Home    Male
21  Student22        ENTC          93   9.6     PG  Female
22  Student23       Civil          76   7.3   Home  Female
23  Student24          CS          86   8.8     PG    Male
24  Student25        AIML          64   6.4   Home  Female
25  Student26    Robotics          79   7.7     PG    Male
26  Student27  Mechanical          73   7.2   Home    Male
27  Student28        ENTC          94   9.7     PG  Female
28  Student29       Civil          67   6.8   Home  Female
29  Student30          CS          85   8.5     PG    Male
30  Student31        AIML          81   8.1   Home    Male
31  Student32    Robotics          84   8.3     PG  Female
32  Student33  Mechanical          70   7.0   Home    Male
33  Student34        ENTC          95   9.8     PG  Female
34  Student35       Civil          78   7.6   Home  Female
35  Student36          CS          90   9.2     PG    Male
36  Student37        AIML          62   6.3   Home    Male
37  Student38    Robotics          86   8.6     PG  Female
38  Student39  Mechanical          74   7.4   Home    Male
39  Student40        ENTC          96   9.9     PG  Female
40  Student41       Civil          69   6.9   Home  Female
41  Student42          CS          91   9.3     PG    Male
42  Student43        AIML          83   8.2   Home  Female
43  Student44    Robotics          88   8.9     PG    Male
44  Student45  Mechanical          72   7.1   Home    Male
45  Student46        ENTC          97  10.0     PG  Female
46  Student47       Civil          75   7.5   Home  Female
47  Student48          CS          92   9.4     PG    Male
48  Student49        AIML          68   6.8   Home    Male
49  Student50    Robotics          87   8.7     PG  Female

In [ ]:
df.fillna(value='DEFAULT')

   Student_ID  Department  Attendance      GPA Living  Gender
0    Student1        AIML          85      8.2   Home    Male
1    Student2    Robotics          78      7.5     PG  Female
2    Student3  Mechanical          65      6.8   Home    Male
3    Student4        ENTC          90      9.1     PG  Female
4    Student5       Civil          72      7.0   Home    Male
5    Student6          CS          88      8.9     PG  Female
6    Student7        AIML          60      6.5   Home  Female
7    Student8    Robotics          82      8.0     PG    Male
8    Student9  Mechanical          75      7.2   Home    Male
9   Student10        ENTC          91  DEFAULT     PG  Female
10  Student11       Civil          68      6.9   Home  Female
11  Student12          CS          87      8.7     PG    Male
12  Student13        AIML          77      7.8   Home    Male
13  Student14    Robotics          83      8.4     PG  Female
14  Student15  Mechanical          69      6.7   Home    Male
15  Student16        ENTC          92      9.5     PG  Female
16  Student17       Civil          74  DEFAULT   Home  Female
17  Student18          CS          89      9.0     PG    Male
18  Student19        AIML          66      6.6   Home    Male
19  Student20    Robotics          80      7.9     PG  Female
20  Student21  Mechanical          71      7.0   Home    Male
21  Student22        ENTC          93      9.6     PG  Female
22  Student23       Civil          76      7.3   Home  Female
23  Student24          CS          86      8.8     PG    Male
24  Student25        AIML          64      6.4   Home  Female
25  Student26    Robotics          79      7.7     PG    Male
26  Student27  Mechanical          73      7.2   Home    Male
27  Student28        ENTC          94      9.7     PG  Female
28  Student29       Civil          67      6.8   Home  Female
29  Student30          CS          85      8.5     PG    Male
30  Student31        AIML          81      8.1   Home    Male
31  Student32    Robotics          84      8.3     PG  Female
32  Student33  Mechanical          70      7.0   Home    Male
33  Student34        ENTC          95      9.8     PG  Female
34  Student35       Civil          78      7.6   Home  Female
35  Student36          CS          90      9.2     PG    Male
36  Student37        AIML          62      6.3   Home    Male
37  Student38    Robotics          86      8.6     PG  Female
38  Student39  Mechanical          74      7.4   Home    Male
39  Student40        ENTC          96      9.9     PG  Female
40  Student41       Civil          69      6.9   Home  Female
41  Student42          CS          91      9.3     PG    Male
42  Student43        AIML          83      8.2   Home  Female
43  Student44    Robotics          88      8.9     PG    Male
44  Student45  Mechanical          72      7.1   Home    Male
45  Student46        ENTC          97     10.0     PG  Female
46  Student47       Civil          75      7.5   Home  Female
47  Student48          CS          92      9.4     PG    Male
48  Student49        AIML          68      6.8   Home    Male
49  Student50    Robotics          87      8.7     PG  Female

In [ ]:
df.fillna(0)

   Student_ID  Department  Attendance   GPA Living  Gender
0    Student1        AIML          85   8.2   Home    Male
1    Student2    Robotics          78   7.5     PG  Female
2    Student3  Mechanical          65   6.8   Home    Male
3    Student4        ENTC          90   9.1     PG  Female
4    Student5       Civil          72   7.0   Home    Male
5    Student6          CS          88   8.9     PG  Female
6    Student7        AIML          60   6.5   Home  Female
7    Student8    Robotics          82   8.0     PG    Male
8    Student9  Mechanical          75   7.2   Home    Male
9   Student10        ENTC          91   0.0     PG  Female
10  Student11       Civil          68   6.9   Home  Female
11  Student12          CS          87   8.7     PG    Male
12  Student13        AIML          77   7.8   Home    Male
13  Student14    Robotics          83   8.4     PG  Female
14  Student15  Mechanical          69   6.7   Home    Male
15  Student16        ENTC          92   9.5     PG  Female
16  Student17       Civil          74   0.0   Home  Female
17  Student18          CS          89   9.0     PG    Male
18  Student19        AIML          66   6.6   Home    Male
19  Student20    Robotics          80   7.9     PG  Female
20  Student21  Mechanical          71   7.0   Home    Male
21  Student22        ENTC          93   9.6     PG  Female
22  Student23       Civil          76   7.3   Home  Female
23  Student24          CS          86   8.8     PG    Male
24  Student25        AIML          64   6.4   Home  Female
25  Student26    Robotics          79   7.7     PG    Male
26  Student27  Mechanical          73   7.2   Home    Male
27  Student28        ENTC          94   9.7     PG  Female
28  Student29       Civil          67   6.8   Home  Female
29  Student30          CS          85   8.5     PG    Male
30  Student31        AIML          81   8.1   Home    Male
31  Student32    Robotics          84   8.3     PG  Female
32  Student33  Mechanical          70   7.0   Home    Male
33  Student34        ENTC          95   9.8     PG  Female
34  Student35       Civil          78   7.6   Home  Female
35  Student36          CS          90   9.2     PG    Male
36  Student37        AIML          62   6.3   Home    Male
37  Student38    Robotics          86   8.6     PG  Female
38  Student39  Mechanical          74   7.4   Home    Male
39  Student40        ENTC          96   9.9     PG  Female
40  Student41       Civil          69   6.9   Home  Female
41  Student42          CS          91   9.3     PG    Male
42  Student43        AIML          83   8.2   Home  Female
43  Student44    Robotics          88   8.9     PG    Male
44  Student45  Mechanical          72   7.1   Home    Male
45  Student46        ENTC          97  10.0     PG  Female
46  Student47       Civil          75   7.5   Home  Female
47  Student48          CS          92   9.4     PG    Male
48  Student49        AIML          68   6.8   Home    Male
49  Student50    Robotics          87   8.7     PG  Female

In [ ]:
df.fillna(df.mean(numeric_only=True))

   Student_ID  Department  Attendance        GPA Living  Gender
0    Student1        AIML          85   8.200000   Home    Male
1    Student2    Robotics          78   7.500000     PG  Female
2    Student3  Mechanical          65   6.800000   Home    Male
3    Student4        ENTC          90   9.100000     PG  Female
4    Student5       Civil          72   7.000000   Home    Male
5    Student6          CS          88   8.900000     PG  Female
6    Student7        AIML          60   6.500000   Home  Female
7    Student8    Robotics          82   8.000000     PG    Male
8    Student9  Mechanical          75   7.200000   Home    Male
9   Student10        ENTC          91   8.014583     PG  Female
10  Student11       Civil          68   6.900000   Home  Female
11  Student12          CS          87   8.700000     PG    Male
12  Student13        AIML          77   7.800000   Home    Male
13  Student14    Robotics          83   8.400000     PG  Female
14  Student15  Mechanical          69   6.700000   Home    Male
15  Student16        ENTC          92   9.500000     PG  Female
16  Student17       Civil          74   8.014583   Home  Female
17  Student18          CS          89   9.000000     PG    Male
18  Student19        AIML          66   6.600000   Home    Male
19  Student20    Robotics          80   7.900000     PG  Female
20  Student21  Mechanical          71   7.000000   Home    Male
21  Student22        ENTC          93   9.600000     PG  Female
22  Student23       Civil          76   7.300000   Home  Female
23  Student24          CS          86   8.800000     PG    Male
24  Student25        AIML          64   6.400000   Home  Female
25  Student26    Robotics          79   7.700000     PG    Male
26  Student27  Mechanical          73   7.200000   Home    Male
27  Student28        ENTC          94   9.700000     PG  Female
28  Student29       Civil          67   6.800000   Home  Female
29  Student30          CS          85   8.500000     PG    Male
30  Student31        AIML          81   8.100000   Home    Male
31  Student32    Robotics          84   8.300000     PG  Female
32  Student33  Mechanical          70   7.000000   Home    Male
33  Student34        ENTC          95   9.800000     PG  Female
34  Student35       Civil          78   7.600000   Home  Female
35  Student36          CS          90   9.200000     PG    Male
36  Student37        AIML          62   6.300000   Home    Male
37  Student38    Robotics          86   8.600000     PG  Female
38  Student39  Mechanical          74   7.400000   Home    Male
39  Student40        ENTC          96   9.900000     PG  Female
40  Student41       Civil          69   6.900000   Home  Female
41  Student42          CS          91   9.300000     PG    Male
42  Student43        AIML          83   8.200000   Home  Female
43  Student44    Robotics          88   8.900000     PG    Male
44  Student45  Mechanical          72   7.100000   Home    Male
45  Student46        ENTC          97  10.000000     PG  Female
46  Student47       Civil          75   7.500000   Home  Female
47  Student48          CS          92   9.400000     PG    Male
48  Student49        AIML          68   6.800000   Home    Male
49  Student50    Robotics          87   8.700000     PG  Female

In [ ]:
df.replace("-",np.nan, inplace=True)
df

   Student_ID  Department  Attendance   GPA Living  Gender
0    Student1        AIML          85   8.2   Home    Male
1    Student2    Robotics          78   7.5     PG  Female
2    Student3  Mechanical          65   6.8   Home    Male
3    Student4        ENTC          90   9.1     PG  Female
4    Student5       Civil          72   7.0   Home    Male
5    Student6          CS          88   8.9     PG  Female
6    Student7        AIML          60   6.5   Home  Female
7    Student8    Robotics          82   8.0     PG    Male
8    Student9  Mechanical          75   7.2   Home    Male
9   Student10        ENTC          91   NaN     PG  Female
10  Student11       Civil          68   6.9   Home  Female
11  Student12          CS          87   8.7     PG    Male
12  Student13        AIML          77   7.8   Home    Male
13  Student14    Robotics          83   8.4     PG  Female
14  Student15  Mechanical          69   6.7   Home    Male
15  Student16        ENTC          92   9.5     PG  Female
16  Student17       Civil          74   NaN   Home  Female
17  Student18          CS          89   9.0     PG    Male
18  Student19        AIML          66   6.6   Home    Male
19  Student20    Robotics          80   7.9     PG  Female
20  Student21  Mechanical          71   7.0   Home    Male
21  Student22        ENTC          93   9.6     PG  Female
22  Student23       Civil          76   7.3   Home  Female
23  Student24          CS          86   8.8     PG    Male
24  Student25        AIML          64   6.4   Home  Female
25  Student26    Robotics          79   7.7     PG    Male
26  Student27  Mechanical          73   7.2   Home    Male
27  Student28        ENTC          94   9.7     PG  Female
28  Student29       Civil          67   6.8   Home  Female
29  Student30          CS          85   8.5     PG    Male
30  Student31        AIML          81   8.1   Home    Male
31  Student32    Robotics          84   8.3     PG  Female
32  Student33  Mechanical          70   7.0   Home    Male
33  Student34        ENTC          95   9.8     PG  Female
34  Student35       Civil          78   7.6   Home  Female
35  Student36          CS          90   9.2     PG    Male
36  Student37        AIML          62   6.3   Home    Male
37  Student38    Robotics          86   8.6     PG  Female
38  Student39  Mechanical          74   7.4   Home    Male
39  Student40        ENTC          96   9.9     PG  Female
40  Student41       Civil          69   6.9   Home  Female
41  Student42          CS          91   9.3     PG    Male
42  Student43        AIML          83   8.2   Home  Female
43  Student44    Robotics          88   8.9     PG    Male
44  Student45  Mechanical          72   7.1   Home    Male
45  Student46        ENTC          97  10.0     PG  Female
46  Student47       Civil          75   7.5   Home  Female
47  Student48          CS          92   9.4     PG    Male
48  Student49        AIML          68   6.8   Home    Male
49  Student50    Robotics          87   8.7     PG  Female

In [ ]:
# convert columns to numeric where needed
df["GPA"] = pd.to_numeric(df["GPA"], errors="coerce")
df

   Student_ID  Department  Attendance   GPA Living  Gender
0    Student1        AIML          85   8.2   Home    Male
1    Student2    Robotics          78   7.5     PG  Female
2    Student3  Mechanical          65   6.8   Home    Male
3    Student4        ENTC          90   9.1     PG  Female
4    Student5       Civil          72   7.0   Home    Male
5    Student6          CS          88   8.9     PG  Female
6    Student7        AIML          60   6.5   Home  Female
7    Student8    Robotics          82   8.0     PG    Male
8    Student9  Mechanical          75   7.2   Home    Male
9   Student10        ENTC          91   NaN     PG  Female
10  Student11       Civil          68   6.9   Home  Female
11  Student12          CS          87   8.7     PG    Male
12  Student13        AIML          77   7.8   Home    Male
13  Student14    Robotics          83   8.4     PG  Female
14  Student15  Mechanical          69   6.7   Home    Male
15  Student16        ENTC          92   9.5     PG  Female
16  Student17       Civil          74   NaN   Home  Female
17  Student18          CS          89   9.0     PG    Male
18  Student19        AIML          66   6.6   Home    Male
19  Student20    Robotics          80   7.9     PG  Female
20  Student21  Mechanical          71   7.0   Home    Male
21  Student22        ENTC          93   9.6     PG  Female
22  Student23       Civil          76   7.3   Home  Female
23  Student24          CS          86   8.8     PG    Male
24  Student25        AIML          64   6.4   Home  Female
25  Student26    Robotics          79   7.7     PG    Male
26  Student27  Mechanical          73   7.2   Home    Male
27  Student28        ENTC          94   9.7     PG  Female
28  Student29       Civil          67   6.8   Home  Female
29  Student30          CS          85   8.5     PG    Male
30  Student31        AIML          81   8.1   Home    Male
31  Student32    Robotics          84   8.3     PG  Female
32  Student33  Mechanical          70   7.0   Home    Male
33  Student34        ENTC          95   9.8     PG  Female
34  Student35       Civil          78   7.6   Home  Female
35  Student36          CS          90   9.2     PG    Male
36  Student37        AIML          62   6.3   Home    Male
37  Student38    Robotics          86   8.6     PG  Female
38  Student39  Mechanical          74   7.4   Home    Male
39  Student40        ENTC          96   9.9     PG  Female
40  Student41       Civil          69   6.9   Home  Female
41  Student42          CS          91   9.3     PG    Male
42  Student43        AIML          83   8.2   Home  Female
43  Student44    Robotics          88   8.9     PG    Male
44  Student45  Mechanical          72   7.1   Home    Male
45  Student46        ENTC          97  10.0     PG  Female
46  Student47       Civil          75   7.5   Home  Female
47  Student48          CS          92   9.4     PG    Male
48  Student49        AIML          68   6.8   Home    Male
49  Student50    Robotics          87   8.7     PG  Female

In [ ]:
#check missing values
print("\nMissing Values:")
print(df.isna().sum())

Missing Values:
Student_ID    0
Department    0
Attendance    0
GPA           2
Living        0
Gender        0
dtype: int64

In [ ]:
# fill missing GPA with mean
df["GPA"].fillna(df["GPA"].mean(), inplace=True)
df

   Student_ID  Department  Attendance        GPA Living  Gender
0    Student1        AIML          85   8.200000   Home    Male
1    Student2    Robotics          78   7.500000     PG  Female
2    Student3  Mechanical          65   6.800000   Home    Male
3    Student4        ENTC          90   9.100000     PG  Female
4    Student5       Civil          72   7.000000   Home    Male
5    Student6          CS          88   8.900000     PG  Female
6    Student7        AIML          60   6.500000   Home  Female
7    Student8    Robotics          82   8.000000     PG    Male
8    Student9  Mechanical          75   7.200000   Home    Male
9   Student10        ENTC          91   8.014583     PG  Female
10  Student11       Civil          68   6.900000   Home  Female
11  Student12          CS          87   8.700000     PG    Male
12  Student13        AIML          77   7.800000   Home    Male
13  Student14    Robotics          83   8.400000     PG  Female
14  Student15  Mechanical          69   6.700000   Home    Male
15  Student16        ENTC          92   9.500000     PG  Female
16  Student17       Civil          74   8.014583   Home  Female
17  Student18          CS          89   9.000000     PG    Male
18  Student19        AIML          66   6.600000   Home    Male
19  Student20    Robotics          80   7.900000     PG  Female
20  Student21  Mechanical          71   7.000000   Home    Male
21  Student22        ENTC          93   9.600000     PG  Female
22  Student23       Civil          76   7.300000   Home  Female
23  Student24          CS          86   8.800000     PG    Male
24  Student25        AIML          64   6.400000   Home  Female
25  Student26    Robotics          79   7.700000     PG    Male
26  Student27  Mechanical          73   7.200000   Home    Male
27  Student28        ENTC          94   9.700000     PG  Female
28  Student29       Civil          67   6.800000   Home  Female
29  Student30          CS          85   8.500000     PG    Male
30  Student31        AIML          81   8.100000   Home    Male
31  Student32    Robotics          84   8.300000     PG  Female
32  Student33  Mechanical          70   7.000000   Home    Male
33  Student34        ENTC          95   9.800000     PG  Female
34  Student35       Civil          78   7.600000   Home  Female
35  Student36          CS          90   9.200000     PG    Male
36  Student37        AIML          62   6.300000   Home    Male
37  Student38    Robotics          86   8.600000     PG  Female
38  Student39  Mechanical          74   7.400000   Home    Male
39  Student40        ENTC          96   9.900000     PG  Female
40  Student41       Civil          69   6.900000   Home  Female
41  Student42          CS          91   9.300000     PG    Male
42  Student43        AIML          83   8.200000   Home  Female
43  Student44    Robotics          88   8.900000     PG    Male
44  Student45  Mechanical          72   7.100000   Home    Male
45  Student46        ENTC          97  10.000000     PG  Female
46  Student47       Civil          75   7.500000   Home  Female
47  Student48          CS          92   9.400000     PG    Male
48  Student49        AIML          68   6.800000   Home    Male
49  Student50    Robotics          87   8.700000     PG  Female

In [ ]:
# fill missing GPA with median
df["GPA"].fillna(df["GPA"].median(), inplace=True)
df

   Student_ID  Department  Attendance        GPA Living  Gender
0    Student1        AIML          85   8.200000   Home    Male
1    Student2    Robotics          78   7.500000     PG  Female
2    Student3  Mechanical          65   6.800000   Home    Male
3    Student4        ENTC          90   9.100000     PG  Female
4    Student5       Civil          72   7.000000   Home    Male
5    Student6          CS          88   8.900000     PG  Female
6    Student7        AIML          60   6.500000   Home  Female
7    Student8    Robotics          82   8.000000     PG    Male
8    Student9  Mechanical          75   7.200000   Home    Male
9   Student10        ENTC          91   8.014583     PG  Female
10  Student11       Civil          68   6.900000   Home  Female
11  Student12          CS          87   8.700000     PG    Male
12  Student13        AIML          77   7.800000   Home    Male
13  Student14    Robotics          83   8.400000     PG  Female
14  Student15  Mechanical          69   6.700000   Home    Male
15  Student16        ENTC          92   9.500000     PG  Female
16  Student17       Civil          74   8.014583   Home  Female
17  Student18          CS          89   9.000000     PG    Male
18  Student19        AIML          66   6.600000   Home    Male
19  Student20    Robotics          80   7.900000     PG  Female
20  Student21  Mechanical          71   7.000000   Home    Male
21  Student22        ENTC          93   9.600000     PG  Female
22  Student23       Civil          76   7.300000   Home  Female
23  Student24          CS          86   8.800000     PG    Male
24  Student25        AIML          64   6.400000   Home  Female
25  Student26    Robotics          79   7.700000     PG    Male
26  Student27  Mechanical          73   7.200000   Home    Male
27  Student28        ENTC          94   9.700000     PG  Female
28  Student29       Civil          67   6.800000   Home  Female
29  Student30          CS          85   8.500000     PG    Male
30  Student31        AIML          81   8.100000   Home    Male
31  Student32    Robotics          84   8.300000     PG  Female
32  Student33  Mechanical          70   7.000000   Home    Male
33  Student34        ENTC          95   9.800000     PG  Female
34  Student35       Civil          78   7.600000   Home  Female
35  Student36          CS          90   9.200000     PG    Male
36  Student37        AIML          62   6.300000   Home    Male
37  Student38    Robotics          86   8.600000     PG  Female
38  Student39  Mechanical          74   7.400000   Home    Male
39  Student40        ENTC          96   9.900000     PG  Female
40  Student41       Civil          69   6.900000   Home  Female
41  Student42          CS          91   9.300000     PG    Male
42  Student43        AIML          83   8.200000   Home  Female
43  Student44    Robotics          88   8.900000     PG    Male
44  Student45  Mechanical          72   7.100000   Home    Male
45  Student46        ENTC          97  10.000000     PG  Female
46  Student47       Civil          75   7.500000   Home  Female
47  Student48          CS          92   9.400000     PG    Male
48  Student49        AIML          68   6.800000   Home    Male
49  Student50    Robotics          87   8.700000     PG  Female

Data Binning and Data Formatting

In [ ]:
# Data Binning
bins1 = [0,70,85,100]
labels1 = ['Low','Medium','High']
df['Attendance_Category'] = pd.cut(df['Attendance'],bins=bins1,labels=labels1)
print(df)

   Student_ID  Department  Attendance        GPA Living  Gender  \
0    Student1        AIML          85   8.200000   Home    Male
1    Student2    Robotics          78   7.500000     PG  Female
2    Student3  Mechanical          65   6.800000   Home    Male
3    Student4        ENTC          90   9.100000     PG  Female
4    Student5       Civil          72   7.000000   Home    Male
5    Student6          CS          88   8.900000     PG  Female
6    Student7        AIML          60   6.500000   Home  Female
7    Student8    Robotics          82   8.000000     PG    Male
8    Student9  Mechanical          75   7.200000   Home    Male
9   Student10        ENTC          91   8.014583     PG  Female
10  Student11       Civil          68   6.900000   Home  Female
11  Student12          CS          87   8.700000     PG    Male
12  Student13        AIML          77   7.800000   Home    Male
13  Student14    Robotics          83   8.400000     PG  Female
14  Student15  Mechanical          69   6.700000   Home    Male
15  Student16        ENTC          92   9.500000     PG  Female
16  Student17       Civil          74   8.014583   Home  Female
17  Student18          CS          89   9.000000     PG    Male
18  Student19        AIML          66   6.600000   Home    Male
19  Student20    Robotics          80   7.900000     PG  Female
20  Student21  Mechanical          71   7.000000   Home    Male
21  Student22        ENTC          93   9.600000     PG  Female
22  Student23       Civil          76   7.300000   Home  Female
23  Student24          CS          86   8.800000     PG    Male
24  Student25        AIML          64   6.400000   Home  Female
25  Student26    Robotics          79   7.700000     PG    Male
26  Student27  Mechanical          73   7.200000   Home    Male
27  Student28        ENTC          94   9.700000     PG  Female
28  Student29       Civil          67   6.800000   Home  Female
29  Student30          CS          85   8.500000     PG    Male
30  Student31        AIML          81   8.100000   Home    Male
31  Student32    Robotics          84   8.300000     PG  Female
32  Student33  Mechanical          70   7.000000   Home    Male
33  Student34        ENTC          95   9.800000     PG  Female
34  Student35       Civil          78   7.600000   Home  Female
35  Student36          CS          90   9.200000     PG    Male
36  Student37        AIML          62   6.300000   Home    Male
37  Student38    Robotics          86   8.600000     PG  Female
38  Student39  Mechanical          74   7.400000   Home    Male
39  Student40        ENTC          96   9.900000     PG  Female
40  Student41       Civil          69   6.900000   Home  Female
41  Student42          CS          91   9.300000     PG    Male
42  Student43        AIML          83   8.200000   Home  Female
43  Student44    Robotics          88   8.900000     PG    Male
44  Student45  Mechanical          72   7.100000   Home    Male
45  Student46        ENTC          97  10.000000     PG  Female
46  Student47       Civil          75   7.500000   Home  Female
47  Student48          CS          92   9.400000     PG    Male
48  Student49        AIML          68   6.800000   Home    Male
49  Student50    Robotics          87   8.700000     PG  Female

   Attendance_Category
0               Medium
1               Medium
2                  Low
3                 High
4               Medium
5                 High
6                  Low
7               Medium
8               Medium
9                 High
10                 Low
11                High
12              Medium
13              Medium
14                 Low
15                High
16              Medium
17                High
18                 Low
19              Medium
20              Medium
21                High
22              Medium
23                High
24                 Low
25              Medium
26              Medium
27                High
28                 Low
29              Medium
30              Medium
31              Medium
32                 Low
33                High
34              Medium
35                High
36                 Low
37                High
38              Medium
39                High
40                 Low
41                High
42              Medium
43                High
44              Medium
45                High
46              Medium
47                High
48                 Low
49                High

In [ ]:
# Converting Datatype
print(df.dtypes)
df['Attendance'] = df['Attendance'].astype(float)
print(df.dtypes)
df

Student_ID               object
Department               object
Attendance              float64
GPA                     float64
Living                   object
Gender                   object
Attendance_Category    category
dtype: object
Student_ID               object
Department               object
Attendance              float64
GPA                     float64
Living                   object
Gender                   object
Attendance_Category    category
dtype: object

,Student_ID,Department,Attendance,GPA,Living,Gender,Attendance_Category
0,Student1,AIML,85.0,8.200000,Home,Male,Medium
1,Student2,Robotics,78.0,7.500000,PG,Female,Medium
2,Student3,Mechanical,65.0,6.800000,Home,Male,Low
3,Student4,ENTC,90.0,9.100000,PG,Female,High
4,Student5,Civil,72.0,7.000000,Home,Male,Medium
5,Student6,CS,88.0,8.900000,PG,Female,High
6,Student7,AIML,60.0,6.500000,Home,Female,Low
7,Student8,Robotics,82.0,8.000000,PG,Male,Medium
8,Student9,Mechanical,75.0,7.200000,Home,Male,Medium
9,Student10,ENTC,91.0,8.014583,PG,Female,High
10,Student11,Civil,68.0,6.900000,Home,Female,Low
11,Student12,CS,87.0,8.700000,PG,Male,High
12,Student13,AIML,77.0,7.800000,Home,Male,Medium
13,Student14,Robotics,83.0,8.400000,PG,Female,Medium
14,Student15,Mechanical,69.0,6.700000,Home,Male,Low
15,Student16,ENTC,92.0,9.500000,PG,Female,High
16,Student17,Civil,74.0,8.014583,Home,Female,Medium
17,Student18,CS,89.0,9.000000,PG,Male,High
18,Student19,AIML,66.0,6.600000,Home,Male,Low
19,Student20,Robotics,80.0,7.900000,PG,Female,Medium
20,Student21,Mechanical,71.0,7.000000,Home,Male,Medium
21,Student22,ENTC,93.0,9.600000,PG,Female,High
22,Student23,Civil,76.0,7.300000,Home,Female,Medium
23,Student24,CS,86.0,8.800000,PG,Male,High
24,Student25,AIML,64.0,6.400000,Home,Female,Low
25,Student26,Robotics,79.0,7.700000,PG,Male,Medium
26,Student27,Mechanical,73.0,7.200000,Home,Male,Medium
27,Student28,ENTC,94.0,9.700000,PG,Female,High
28,Student29,Civil,67.0,6.800000,Home,Female,Low
29,Student30,CS,85.0,8.500000,PG,Male,Medium
30,Student31,AIML,81.0,8.100000,Home,Male,Medium
31,Student32,Robotics,84.0,8.300000,PG,Female,Medium
32,Student33,Mechanical,70.0,7.000000,Home,Male,Low
33,Student34,ENTC,95.0,9.800000,PG,Female,High
34,Student35,Civil,78.0,7.600000,Home,Female,Medium
35,Student36,CS,90.0,9.200000,PG,Male,High
36,Student37,AIML,62.0,6.300000,Home,Male,Low
37,Student38,Robotics,86.0,8.600000,PG,Female,High
38,Student39,Mechanical,74.0,7.400000,Home,Male,Medium
39,Student40,ENTC,96.0,9.900000,PG,Female,High
40,Student41,Civil,69.0,6.900000,Home,Female,Low
41,Student42,CS,91.0,9.300000,PG,Male,High
42,Student43,AIML,83.0,8.200000,Home,Female,Medium
43,Student44,Robotics,88.0,8.900000,PG,Male,High
44,Student45,Mechanical,72.0,7.100000,Home,Male,Medium
45,Student46,ENTC,97.0,10.000000,PG,Female,High
46,Student47,Civil,75.0,7.500000,Home,Female,Medium
47,Student48,CS,92.0,9.400000,PG,Male,High
48,Student49,AIML,68.0,6.800000,Home,Male,Low
49,Student50,Robotics,87.0,8.700000,PG,Female,High

In [ ]:
#convert text to uppercase
df['Living'] = df['Living'].str.upper()
print(df)

   Student_ID  Department  Attendance        GPA Living  Gender  \
0    Student1        AIML        85.0   8.200000   HOME    Male
1    Student2    Robotics        78.0   7.500000     PG  Female
2    Student3  Mechanical        65.0   6.800000   HOME    Male
3    Student4        ENTC        90.0   9.100000     PG  Female
4    Student5       Civil        72.0   7.000000   HOME    Male
5    Student6          CS        88.0   8.900000     PG  Female
6    Student7        AIML        60.0   6.500000   HOME  Female
7    Student8    Robotics        82.0   8.000000     PG    Male
8    Student9  Mechanical        75.0   7.200000   HOME    Male
9   Student10        ENTC        91.0   8.014583     PG  Female
10  Student11       Civil        68.0   6.900000   HOME  Female
11  Student12          CS        87.0   8.700000     PG    Male
12  Student13        AIML        77.0   7.800000   HOME    Male
13  Student14    Robotics        83.0   8.400000     PG  Female
14  Student15  Mechanical        69.0   6.700000   HOME    Male
15  Student16        ENTC        92.0   9.500000     PG  Female
16  Student17       Civil        74.0   8.014583   HOME  Female
17  Student18          CS        89.0   9.000000     PG    Male
18  Student19        AIML        66.0   6.600000   HOME    Male
19  Student20    Robotics        80.0   7.900000     PG  Female
20  Student21  Mechanical        71.0   7.000000   HOME    Male
21  Student22        ENTC        93.0   9.600000     PG  Female
22  Student23       Civil        76.0   7.300000   HOME  Female
23  Student24          CS        86.0   8.800000     PG    Male
24  Student25        AIML        64.0   6.400000   HOME  Female
25  Student26    Robotics        79.0   7.700000     PG    Male
26  Student27  Mechanical        73.0   7.200000   HOME    Male
27  Student28        ENTC        94.0   9.700000     PG  Female
28  Student29       Civil        67.0   6.800000   HOME  Female
29  Student30          CS        85.0   8.500000     PG    Male
30  Student31        AIML        81.0   8.100000   HOME    Male
31  Student32    Robotics        84.0   8.300000     PG  Female
32  Student33  Mechanical        70.0   7.000000   HOME    Male
33  Student34        ENTC        95.0   9.800000     PG  Female
34  Student35       Civil        78.0   7.600000   HOME  Female
35  Student36          CS        90.0   9.200000     PG    Male
36  Student37        AIML        62.0   6.300000   HOME    Male
37  Student38    Robotics        86.0   8.600000     PG  Female
38  Student39  Mechanical        74.0   7.400000   HOME    Male
39  Student40        ENTC        96.0   9.900000     PG  Female
40  Student41       Civil        69.0   6.900000   HOME  Female
41  Student42          CS        91.0   9.300000     PG    Male
42  Student43        AIML        83.0   8.200000   HOME  Female
43  Student44    Robotics        88.0   8.900000     PG    Male
44  Student45  Mechanical        72.0   7.100000   HOME    Male
45  Student46        ENTC        97.0  10.000000     PG  Female
46  Student47       Civil        75.0   7.500000   HOME  Female
47  Student48          CS        92.0   9.400000     PG    Male
48  Student49        AIML        68.0   6.800000   HOME    Male
49  Student50    Robotics        87.0   8.700000     PG  Female

   Attendance_Category
0               Medium
1               Medium
2                  Low
3                 High
4               Medium
5                 High
6                  Low
7               Medium
8               Medium
9                 High
10                 Low
11                High
12              Medium
13              Medium
14                 Low
15                High
16              Medium
17                High
18                 Low
19              Medium
20              Medium
21                High
22              Medium
23                High
24                 Low
25              Medium
26              Medium
27                High
28                 Low
29              Medium
30              Medium
31              Medium
32                 Low
33                High
34              Medium
35                High
36                 Low
37                High
38              Medium
39                High
40                 Low
41                High
42              Medium
43                High
44              Medium
45                High
46              Medium
47                High
48                 Low
49                High

In [ ]:
#Rounding Values
df['Attendance'] = df['Attendance'].round(2)
print(df)

   Student_ID  Department  Attendance        GPA Living  Gender  \
0    Student1        AIML        85.0   8.200000   HOME    Male
1    Student2    Robotics        78.0   7.500000     PG  Female
2    Student3  Mechanical        65.0   6.800000   HOME    Male
3    Student4        ENTC        90.0   9.100000     PG  Female
4    Student5       Civil        72.0   7.000000   HOME    Male
5    Student6          CS        88.0   8.900000     PG  Female
6    Student7        AIML        60.0   6.500000   HOME  Female
7    Student8    Robotics        82.0   8.000000     PG    Male
8    Student9  Mechanical        75.0   7.200000   HOME    Male
9   Student10        ENTC        91.0   8.014583     PG  Female
10  Student11       Civil        68.0   6.900000   HOME  Female
11  Student12          CS        87.0   8.700000     PG    Male
12  Student13        AIML        77.0   7.800000   HOME    Male
13  Student14    Robotics        83.0   8.400000     PG  Female
14  Student15  Mechanical        69.0   6.700000   HOME    Male
15  Student16        ENTC        92.0   9.500000     PG  Female
16  Student17       Civil        74.0   8.014583   HOME  Female
17  Student18          CS        89.0   9.000000     PG    Male
18  Student19        AIML        66.0   6.600000   HOME    Male
19  Student20    Robotics        80.0   7.900000     PG  Female
20  Student21  Mechanical        71.0   7.000000   HOME    Male
21  Student22        ENTC        93.0   9.600000     PG  Female
22  Student23       Civil        76.0   7.300000   HOME  Female
23  Student24          CS        86.0   8.800000     PG    Male
24  Student25        AIML        64.0   6.400000   HOME  Female
25  Student26    Robotics        79.0   7.700000     PG    Male
26  Student27  Mechanical        73.0   7.200000   HOME    Male
27  Student28        ENTC        94.0   9.700000     PG  Female
28  Student29       Civil        67.0   6.800000   HOME  Female
29  Student30          CS        85.0   8.500000     PG    Male
30  Student31        AIML        81.0   8.100000   HOME    Male
31  Student32    Robotics        84.0   8.300000     PG  Female
32  Student33  Mechanical        70.0   7.000000   HOME    Male
33  Student34        ENTC        95.0   9.800000     PG  Female
34  Student35       Civil        78.0   7.600000   HOME  Female
35  Student36          CS        90.0   9.200000     PG    Male
36  Student37        AIML        62.0   6.300000   HOME    Male
37  Student38    Robotics        86.0   8.600000     PG  Female
38  Student39  Mechanical        74.0   7.400000   HOME    Male
39  Student40        ENTC        96.0   9.900000     PG  Female
40  Student41       Civil        69.0   6.900000   HOME  Female
41  Student42          CS        91.0   9.300000     PG    Male
42  Student43        AIML        83.0   8.200000   HOME  Female
43  Student44    Robotics        88.0   8.900000     PG    Male
44  Student45  Mechanical        72.0   7.100000   HOME    Male
45  Student46        ENTC        97.0  10.000000     PG  Female
46  Student47       Civil        75.0   7.500000   HOME  Female
47  Student48          CS        92.0   9.400000     PG    Male
48  Student49        AIML        68.0   6.800000   HOME    Male
49  Student50    Robotics        87.0   8.700000     PG  Female

   Attendance_Category
0               Medium
1               Medium
2                  Low
3                 High
4               Medium
5                 High
6                  Low
7               Medium
8               Medium
9                 High
10                 Low
11                High
12              Medium
13              Medium
14                 Low
15                High
16              Medium
17                High
18                 Low
19              Medium
20              Medium
21                High
22              Medium
23                High
24                 Low
25              Medium
26              Medium
27                High
28                 Low
29              Medium
30              Medium
31              Medium
32                 Low
33                High
34              Medium
35                High
36                 Low
37                High
38              Medium
39                High
40                 Low
41                High
42              Medium
43                High
44              Medium
45                High
46              Medium
47                High
48                 Low
49                High

In [ ]:
#display unique values
print(df['Department'].unique())

['AIML' 'Robotics' 'Mechanical' 'ENTC' 'Civil' 'CS']

In [ ]:
# Count of categories
print(df['Department'].value_counts())
df

Department
AIML          9
Robotics      9
Mechanical    8
ENTC          8
Civil         8
CS            8
Name: count, dtype: int64

,Student_ID,Department,Attendance,GPA,Living,Gender,Attendance_Category
0,Student1,AIML,85.0,8.200000,HOME,Male,Medium
1,Student2,Robotics,78.0,7.500000,PG,Female,Medium
2,Student3,Mechanical,65.0,6.800000,HOME,Male,Low
3,Student4,ENTC,90.0,9.100000,PG,Female,High
4,Student5,Civil,72.0,7.000000,HOME,Male,Medium
5,Student6,CS,88.0,8.900000,PG,Female,High
6,Student7,AIML,60.0,6.500000,HOME,Female,Low
7,Student8,Robotics,82.0,8.000000,PG,Male,Medium
8,Student9,Mechanical,75.0,7.200000,HOME,Male,Medium
9,Student10,ENTC,91.0,8.014583,PG,Female,High
10,Student11,Civil,68.0,6.900000,HOME,Female,Low
11,Student12,CS,87.0,8.700000,PG,Male,High
12,Student13,AIML,77.0,7.800000,HOME,Male,Medium
13,Student14,Robotics,83.0,8.400000,PG,Female,Medium
14,Student15,Mechanical,69.0,6.700000,HOME,Male,Low
15,Student16,ENTC,92.0,9.500000,PG,Female,High
16,Student17,Civil,74.0,8.014583,HOME,Female,Medium
17,Student18,CS,89.0,9.000000,PG,Male,High
18,Student19,AIML,66.0,6.600000,HOME,Male,Low
19,Student20,Robotics,80.0,7.900000,PG,Female,Medium
20,Student21,Mechanical,71.0,7.000000,HOME,Male,Medium
21,Student22,ENTC,93.0,9.600000,PG,Female,High
22,Student23,Civil,76.0,7.300000,HOME,Female,Medium
23,Student24,CS,86.0,8.800000,PG,Male,High
24,Student25,AIML,64.0,6.400000,HOME,Female,Low
25,Student26,Robotics,79.0,7.700000,PG,Male,Medium
26,Student27,Mechanical,73.0,7.200000,HOME,Male,Medium
27,Student28,ENTC,94.0,9.700000,PG,Female,High
28,Student29,Civil,67.0,6.800000,HOME,Female,Low
29,Student30,CS,85.0,8.500000,PG,Male,Medium
30,Student31,AIML,81.0,8.100000,HOME,Male,Medium
31,Student32,Robotics,84.0,8.300000,PG,Female,Medium
32,Student33,Mechanical,70.0,7.000000,HOME,Male,Low
33,Student34,ENTC,95.0,9.800000,PG,Female,High
34,Student35,Civil,78.0,7.600000,HOME,Female,Medium
35,Student36,CS,90.0,9.200000,PG,Male,High
36,Student37,AIML,62.0,6.300000,HOME,Male,Low
37,Student38,Robotics,86.0,8.600000,PG,Female,High
38,Student39,Mechanical,74.0,7.400000,HOME,Male,Medium
39,Student40,ENTC,96.0,9.900000,PG,Female,High
40,Student41,Civil,69.0,6.900000,HOME,Female,Low
41,Student42,CS,91.0,9.300000,PG,Male,High
42,Student43,AIML,83.0,8.200000,HOME,Female,Medium
43,Student44,Robotics,88.0,8.900000,PG,Male,High
44,Student45,Mechanical,72.0,7.100000,HOME,Male,Medium
45,Student46,ENTC,97.0,10.000000,PG,Female,High
46,Student47,Civil,75.0,7.500000,HOME,Female,Medium
47,Student48,CS,92.0,9.400000,PG,Male,High
48,Student49,AIML,68.0,6.800000,HOME,Male,Low
49,Student50,Robotics,87.0,8.700000,PG,Female,High

Data Normalization and data type conversion

In [ ]:
#Min-Max Normalization

df['GPA_MinMax'] = (df['GPA'] - df['GPA'].min()) / (df['GPA'].max() - df['GPA'].min())
print("\nMin-Max Normalized GPA")
print(df[['Student_ID','GPA','GPA_MinMax']])

Min-Max Normalized GPA
   Student_ID        GPA  GPA_MinMax
0    Student1   8.200000    0.513514
1    Student2   7.500000    0.324324
2    Student3   6.800000    0.135135
3    Student4   9.100000    0.756757
4    Student5   7.000000    0.189189
5    Student6   8.900000    0.702703
6    Student7   6.500000    0.054054
7    Student8   8.000000    0.459459
8    Student9   7.200000    0.243243
9   Student10   8.014583    0.463401
10  Student11   6.900000    0.162162
11  Student12   8.700000    0.648649
12  Student13   7.800000    0.405405
13  Student14   8.400000    0.567568
14  Student15   6.700000    0.108108
15  Student16   9.500000    0.864865
16  Student17   8.014583    0.463401
17  Student18   9.000000    0.729730
18  Student19   6.600000    0.081081
19  Student20   7.900000    0.432432
20  Student21   7.000000    0.189189
21  Student22   9.600000    0.891892
22  Student23   7.300000    0.270270
23  Student24   8.800000    0.675676
24  Student25   6.400000    0.027027
25  Student26   7.700000    0.378378
26  Student27   7.200000    0.243243
27  Student28   9.700000    0.918919
28  Student29   6.800000    0.135135
29  Student30   8.500000    0.594595
30  Student31   8.100000    0.486486
31  Student32   8.300000    0.540541
32  Student33   7.000000    0.189189
33  Student34   9.800000    0.945946
34  Student35   7.600000    0.351351
35  Student36   9.200000    0.783784
36  Student37   6.300000    0.000000
37  Student38   8.600000    0.621622
38  Student39   7.400000    0.297297
39  Student40   9.900000    0.972973
40  Student41   6.900000    0.162162
41  Student42   9.300000    0.810811
42  Student43   8.200000    0.513514
43  Student44   8.900000    0.702703
44  Student45   7.100000    0.216216
45  Student46  10.000000    1.000000
46  Student47   7.500000    0.324324
47  Student48   9.400000    0.837838
48  Student49   6.800000    0.135135
49  Student50   8.700000    0.648649

In [ ]:
#Normalize Multiple Columns
cols = ['Attendance','GPA']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
    Attendance       GPA
0     0.675676  0.513514
1     0.486486  0.324324
2     0.135135  0.135135
3     0.810811  0.756757
4     0.324324  0.189189
5     0.756757  0.702703
6     0.000000  0.054054
7     0.594595  0.459459
8     0.405405  0.243243
9     0.837838  0.463401
10    0.216216  0.162162
11    0.729730  0.648649
12    0.459459  0.405405
13    0.621622  0.567568
14    0.243243  0.108108
15    0.864865  0.864865
16    0.378378  0.463401
17    0.783784  0.729730
18    0.162162  0.081081
19    0.540541  0.432432
20    0.297297  0.189189
21    0.891892  0.891892
22    0.432432  0.270270
23    0.702703  0.675676
24    0.108108  0.027027
25    0.513514  0.378378
26    0.351351  0.243243
27    0.918919  0.918919
28    0.189189  0.135135
29    0.675676  0.594595
30    0.567568  0.486486
31    0.648649  0.540541
32    0.270270  0.189189
33    0.945946  0.945946
34    0.486486  0.351351
35    0.810811  0.783784
36    0.054054  0.000000
37    0.702703  0.621622
38    0.378378  0.297297
39    0.972973  0.972973
40    0.243243  0.162162
41    0.837838  0.810811
42    0.621622  0.513514
43    0.756757  0.702703
44    0.324324  0.216216
45    1.000000  1.000000
46    0.405405  0.324324
47    0.864865  0.837838
48    0.216216  0.135135
49    0.729730  0.648649

In [ ]:
# Z-score Normalization
df['GPA_Zscore'] = (df['GPA'] - df['GPA'].mean()) / df['GPA'].std()
print("\nZ-score Normalized GPA")
print(df[['Student_ID','GPA','GPA_Zscore']])

Z-score Normalized GPA
   Student_ID        GPA  GPA_Zscore
0    Student1   8.200000    0.175235
1    Student2   7.500000   -0.486325
2    Student3   6.800000   -1.147885
3    Student4   9.100000    1.025811
4    Student5   7.000000   -0.958868
5    Student6   8.900000    0.836794
6    Student7   6.500000   -1.431410
7    Student8   8.000000   -0.013782
8    Student9   7.200000   -0.769851
9   Student10   8.014583    0.000000
10  Student11   6.900000   -1.053376
11  Student12   8.700000    0.647777
12  Student13   7.800000   -0.202800
13  Student14   8.400000    0.364252
14  Student15   6.700000   -1.242393
15  Student16   9.500000    1.403845
16  Student17   8.014583    0.000000
17  Student18   9.000000    0.931303
18  Student19   6.600000   -1.336902
19  Student20   7.900000   -0.108291
20  Student21   7.000000   -0.958868
21  Student22   9.600000    1.498354
22  Student23   7.300000   -0.675342
23  Student24   8.800000    0.742286
24  Student25   6.400000   -1.525919
25  Student26   7.700000   -0.297308
26  Student27   7.200000   -0.769851
27  Student28   9.700000    1.592862
28  Student29   6.800000   -1.147885
29  Student30   8.500000    0.458760
30  Student31   8.100000    0.080726
31  Student32   8.300000    0.269743
32  Student33   7.000000   -0.958868
33  Student34   9.800000    1.687371
34  Student35   7.600000   -0.391817
35  Student36   9.200000    1.120320
36  Student37   6.300000   -1.620427
37  Student38   8.600000    0.553269
38  Student39   7.400000   -0.580834
39  Student40   9.900000    1.781879
40  Student41   6.900000   -1.053376
41  Student42   9.300000    1.214828
42  Student43   8.200000    0.175235
43  Student44   8.900000    0.836794
44  Student45   7.100000   -0.864359
45  Student46  10.000000    1.876388
46  Student47   7.500000   -0.486325
47  Student48   9.400000    1.309337
48  Student49   6.800000   -1.147885
49  Student50   8.700000    0.647777

In [ ]:
# Decimal Scaling
df['GPA_DS'] = df['GPA'] / 100000
print("\nDecimal Scaled GPA")
print(df[['GPA','GPA_DS']])

Decimal Scaled GPA
          GPA    GPA_DS
0    8.200000  0.000082
1    7.500000  0.000075
2    6.800000  0.000068
3    9.100000  0.000091
4    7.000000  0.000070
5    8.900000  0.000089
6    6.500000  0.000065
7    8.000000  0.000080
8    7.200000  0.000072
9    8.014583  0.000080
10   6.900000  0.000069
11   8.700000  0.000087
12   7.800000  0.000078
13   8.400000  0.000084
14   6.700000  0.000067
15   9.500000  0.000095
16   8.014583  0.000080
17   9.000000  0.000090
18   6.600000  0.000066
19   7.900000  0.000079
20   7.000000  0.000070
21   9.600000  0.000096
22   7.300000  0.000073
23   8.800000  0.000088
24   6.400000  0.000064
25   7.700000  0.000077
26   7.200000  0.000072
27   9.700000  0.000097
28   6.800000  0.000068
29   8.500000  0.000085
30   8.100000  0.000081
31   8.300000  0.000083
32   7.000000  0.000070
33   9.800000  0.000098
34   7.600000  0.000076
35   9.200000  0.000092
36   6.300000  0.000063
37   8.600000  0.000086
38   7.400000  0.000074
39   9.900000  0.000099
40   6.900000  0.000069
41   9.300000  0.000093
42   8.200000  0.000082
43   8.900000  0.000089
44   7.100000  0.000071
45  10.000000  0.000100
46   7.500000  0.000075
47   9.400000  0.000094
48   6.800000  0.000068
49   8.700000  0.000087

In [ ]:
# Label Encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
print(df)

   Student_ID  Department  Attendance        GPA Living  Gender  \
0    Student1        AIML        85.0   8.200000   HOME       1
1    Student2    Robotics        78.0   7.500000     PG       0
2    Student3  Mechanical        65.0   6.800000   HOME       1
3    Student4        ENTC        90.0   9.100000     PG       0
4    Student5       Civil        72.0   7.000000   HOME       1
5    Student6          CS        88.0   8.900000     PG       0
6    Student7        AIML        60.0   6.500000   HOME       0
7    Student8    Robotics        82.0   8.000000     PG       1
8    Student9  Mechanical        75.0   7.200000   HOME       1
9   Student10        ENTC        91.0   8.014583     PG       0
10  Student11       Civil        68.0   6.900000   HOME       0
11  Student12          CS        87.0   8.700000     PG       1
12  Student13        AIML        77.0   7.800000   HOME       1
13  Student14    Robotics        83.0   8.400000     PG       0
14  Student15  Mechanical        69.0   6.700000   HOME       1
15  Student16        ENTC        92.0   9.500000     PG       0
16  Student17       Civil        74.0   8.014583   HOME       0
17  Student18          CS        89.0   9.000000     PG       1
18  Student19        AIML        66.0   6.600000   HOME       1
19  Student20    Robotics        80.0   7.900000     PG       0
20  Student21  Mechanical        71.0   7.000000   HOME       1
21  Student22        ENTC        93.0   9.600000     PG       0
22  Student23       Civil        76.0   7.300000   HOME       0
23  Student24          CS        86.0   8.800000     PG       1
24  Student25        AIML        64.0   6.400000   HOME       0
25  Student26    Robotics        79.0   7.700000     PG       1
26  Student27  Mechanical        73.0   7.200000   HOME       1
27  Student28        ENTC        94.0   9.700000     PG       0
28  Student29       Civil        67.0   6.800000   HOME       0
29  Student30          CS        85.0   8.500000     PG       1
30  Student31        AIML        81.0   8.100000   HOME       1
31  Student32    Robotics        84.0   8.300000     PG       0
32  Student33  Mechanical        70.0   7.000000   HOME       1
33  Student34        ENTC        95.0   9.800000     PG       0
34  Student35       Civil        78.0   7.600000   HOME       0
35  Student36          CS        90.0   9.200000     PG       1
36  Student37        AIML        62.0   6.300000   HOME       1
37  Student38    Robotics        86.0   8.600000     PG       0
38  Student39  Mechanical        74.0   7.400000   HOME       1
39  Student40        ENTC        96.0   9.900000     PG       0
40  Student41       Civil        69.0   6.900000   HOME       0
41  Student42          CS        91.0   9.300000     PG       1
42  Student43        AIML        83.0   8.200000   HOME       0
43  Student44    Robotics        88.0   8.900000     PG       1
44  Student45  Mechanical        72.0   7.100000   HOME       1
45  Student46        ENTC        97.0  10.000000     PG       0
46  Student47       Civil        75.0   7.500000   HOME       0
47  Student48          CS        92.0   9.400000     PG       1
48  Student49        AIML        68.0   6.800000   HOME       1
49  Student50    Robotics        87.0   8.700000     PG       0

   Attendance_Category  GPA_MinMax  GPA_Zscore    GPA_DS
0               Medium    0.513514    0.175235  0.000082
1               Medium    0.324324   -0.486325  0.000075
2                  Low    0.135135   -1.147885  0.000068
3                 High    0.756757    1.025811  0.000091
4               Medium    0.189189   -0.958868  0.000070
5                 High    0.702703    0.836794  0.000089
6                  Low    0.054054   -1.431410  0.000065
7               Medium    0.459459   -0.013782  0.000080
8               Medium    0.243243   -0.769851  0.000072
9                 High    0.463401    0.000000  0.000080
10                 Low    0.162162   -1.053376  0.000069
11                High    0.648649    0.647777  0.000087
12              Medium    0.405405   -0.202800  0.000078
13              Medium    0.567568    0.364252  0.000084
14                 Low    0.108108   -1.242393  0.000067
15                High    0.864865    1.403845  0.000095
16              Medium    0.463401    0.000000  0.000080
17                High    0.729730    0.931303  0.000090
18                 Low    0.081081   -1.336902  0.000066
19              Medium    0.432432   -0.108291  0.000079
20              Medium    0.189189   -0.958868  0.000070
21                High    0.891892    1.498354  0.000096
22              Medium    0.270270   -0.675342  0.000073
23                High    0.675676    0.742286  0.000088
24                 Low    0.027027   -1.525919  0.000064
25              Medium    0.378378   -0.297308  0.000077
26              Medium    0.243243   -0.769851  0.000072
27                High    0.918919    1.592862  0.000097
28                 Low    0.135135   -1.147885  0.000068
29              Medium    0.594595    0.458760  0.000085
30              Medium    0.486486    0.080726  0.000081
31              Medium    0.540541    0.269743  0.000083
32                 Low    0.189189   -0.958868  0.000070
33                High    0.945946    1.687371  0.000098
34              Medium    0.351351   -0.391817  0.000076
35                High    0.783784    1.120320  0.000092
36                 Low    0.000000   -1.620427  0.000063
37                High    0.621622    0.553269  0.000086
38              Medium    0.297297   -0.580834  0.000074
39                High    0.972973    1.781879  0.000099
40                 Low    0.162162   -1.053376  0.000069
41                High    0.810811    1.214828  0.000093
42              Medium    0.513514    0.175235  0.000082
43                High    0.702703    0.836794  0.000089
44              Medium    0.216216   -0.864359  0.000071
45                High    1.000000    1.876388  0.000100
46              Medium    0.324324   -0.486325  0.000075
47                High    0.837838    1.309337  0.000094
48                 Low    0.135135   -1.147885  0.000068
49                High    0.648649    0.647777  0.000087

In [ ]:
# One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Department'])
print(df_encoded)

   Student_ID  Attendance        GPA Living  Gender Attendance_Category  \
0    Student1        85.0   8.200000   HOME       1              Medium
1    Student2        78.0   7.500000     PG       0              Medium
2    Student3        65.0   6.800000   HOME       1                 Low
3    Student4        90.0   9.100000     PG       0                High
4    Student5        72.0   7.000000   HOME       1              Medium
5    Student6        88.0   8.900000     PG       0                High
6    Student7        60.0   6.500000   HOME       0                 Low
7    Student8        82.0   8.000000     PG       1              Medium
8    Student9        75.0   7.200000   HOME       1              Medium
9   Student10        91.0   8.014583     PG       0                High
10  Student11        68.0   6.900000   HOME       0                 Low
11  Student12        87.0   8.700000     PG       1                High
12  Student13        77.0   7.800000   HOME       1              Medium
13  Student14        83.0   8.400000     PG       0              Medium
14  Student15        69.0   6.700000   HOME       1                 Low
15  Student16        92.0   9.500000     PG       0                High
16  Student17        74.0   8.014583   HOME       0              Medium
17  Student18        89.0   9.000000     PG       1                High
18  Student19        66.0   6.600000   HOME       1                 Low
19  Student20        80.0   7.900000     PG       0              Medium
20  Student21        71.0   7.000000   HOME       1              Medium
21  Student22        93.0   9.600000     PG       0                High
22  Student23        76.0   7.300000   HOME       0              Medium
23  Student24        86.0   8.800000     PG       1                High
24  Student25        64.0   6.400000   HOME       0                 Low
25  Student26        79.0   7.700000     PG       1              Medium
26  Student27        73.0   7.200000   HOME       1              Medium
27  Student28        94.0   9.700000     PG       0                High
28  Student29        67.0   6.800000   HOME       0                 Low
29  Student30        85.0   8.500000     PG       1              Medium
30  Student31        81.0   8.100000   HOME       1              Medium
31  Student32        84.0   8.300000     PG       0              Medium
32  Student33        70.0   7.000000   HOME       1                 Low
33  Student34        95.0   9.800000     PG       0                High
34  Student35        78.0   7.600000   HOME       0              Medium
35  Student36        90.0   9.200000     PG       1                High
36  Student37        62.0   6.300000   HOME       1                 Low
37  Student38        86.0   8.600000     PG       0                High
38  Student39        74.0   7.400000   HOME       1              Medium
39  Student40        96.0   9.900000     PG       0                High
40  Student41        69.0   6.900000   HOME       0                 Low
41  Student42        91.0   9.300000     PG       1                High
42  Student43        83.0   8.200000   HOME       0              Medium
43  Student44        88.0   8.900000     PG       1                High
44  Student45        72.0   7.100000   HOME       1              Medium
45  Student46        97.0  10.000000     PG       0                High
46  Student47        75.0   7.500000   HOME       0              Medium
47  Student48        92.0   9.400000     PG       1                High
48  Student49        68.0   6.800000   HOME       1                 Low
49  Student50        87.0   8.700000     PG       0                High

    GPA_MinMax  GPA_Zscore    GPA_DS  Department_AIML  Department_CS  \
0     0.513514    0.175235  0.000082             True          False
1     0.324324   -0.486325  0.000075            False          False
2     0.135135   -1.147885  0.000068            False          False
3     0.756757    1.025811  0.000091            False          False
4     0.189189   -0.958868  0.000070            False          False
5     0.702703    0.836794  0.000089            False           True
6     0.054054   -1.431410  0.000065             True          False
7     0.459459   -0.013782  0.000080            False          False
8     0.243243   -0.769851  0.000072            False          False
9     0.463401    0.000000  0.000080            False          False
10    0.162162   -1.053376  0.000069            False          False
11    0.648649    0.647777  0.000087            False           True
12    0.405405   -0.202800  0.000078             True          False
13    0.567568    0.364252  0.000084            False          False
14    0.108108   -1.242393  0.000067            False          False
15    0.864865    1.403845  0.000095            False          False
16    0.463401    0.000000  0.000080            False          False
17    0.729730    0.931303  0.000090            False           True
18    0.081081   -1.336902  0.000066             True          False
19    0.432432   -0.108291  0.000079            False          False
20    0.189189   -0.958868  0.000070            False          False
21    0.891892    1.498354  0.000096            False          False
22    0.270270   -0.675342  0.000073            False          False
23    0.675676    0.742286  0.000088            False           True
24    0.027027   -1.525919  0.000064             True          False
25    0.378378   -0.297308  0.000077            False          False
26    0.243243   -0.769851  0.000072            False          False
27    0.918919    1.592862  0.000097            False          False
28    0.135135   -1.147885  0.000068            False          False
29    0.594595    0.458760  0.000085            False           True
30    0.486486    0.080726  0.000081             True          False
31    0.540541    0.269743  0.000083            False          False
32    0.189189   -0.958868  0.000070            False          False
33    0.945946    1.687371  0.000098            False          False
34    0.351351   -0.391817  0.000076            False          False
35    0.783784    1.120320  0.000092            False           True
36    0.000000   -1.620427  0.000063             True          False
37    0.621622    0.553269  0.000086            False          False
38    0.297297   -0.580834  0.000074            False          False
39    0.972973    1.781879  0.000099            False          False
40    0.162162   -1.053376  0.000069            False          False
41    0.810811    1.214828  0.000093            False           True
42    0.513514    0.175235  0.000082             True          False
43    0.702703    0.836794  0.000089            False          False
44    0.216216   -0.864359  0.000071            False          False
45    1.000000    1.876388  0.000100            False          False
46    0.324324   -0.486325  0.000075            False          False
47    0.837838    1.309337  0.000094            False           True
48    0.135135   -1.147885  0.000068             True          False
49    0.648649    0.647777  0.000087            False          False

    Department_Civil  Department_ENTC  Department_Mechanical  \
0              False            False                  False
1              False            False                  False
2              False            False                   True
3              False             True                  False
4               True            False                  False
5              False            False                  False
6              False            False                  False
7              False            False                  False
8              False            False                   True
9              False             True                  False
10              True            False                  False
11             False            False                  False
12             False            False                  False
13             False            False                  False
14             False            False                   True
15             False             True                  False
16              True            False                  False
17             False            False                  False
18             False            False                  False
19             False            False                  False
20             False            False                   True
21             False             True                  False
22              True            False                  False
23             False            False                  False
24             False            False                  False
25             False            False                  False
26             False            False                   True
27             False             True                  False
28              True            False                  False
29             False            False                  False
30             False            False                  False
31             False            False                  False
32             False            False                   True
33             False             True                  False
34              True            False                  False
35             False            False                  False
36             False            False                  False
37             False            False                  False
38             False            False                   True
39             False             True                  False
40              True            False                  False
41             False            False                  False
42             False            False                  False
43             False            False                  False
44             False            False                   True
45             False             True                  False
46              True            False                  False
47             False            False                  False
48             False            False                  False
49             False            False                  False

    Department_Robotics
0                 False
1                  True
2                 False
3                 False
4                 False
5                 False
6                 False
7                  True
8                 False
9                 False
10                False
11                False
12                False
13                 True
14                False
15                False
16                False
17                False
18                False
19                 True
20                False
21                False
22                False
23                False
24                False
25                 True
26                False
27                False
28                False
29                False
30                False
31                 True
32                False
33                False
34                False
35                False
36                False
37                 True
38                False
39                False
40                False
41                False
42                False
43                 True
44                False
45                False
46                False
47                False
48                False
49                 True

In [ ]:
# Dummy Encoding (Drop First)
df_dummy = pd.get_dummies(df, columns=['Department'], drop_first=True)
print(df_dummy)

   Student_ID  Attendance        GPA Living  Gender Attendance_Category  \
0    Student1        85.0   8.200000   HOME       1              Medium
1    Student2        78.0   7.500000     PG       0              Medium
2    Student3        65.0   6.800000   HOME       1                 Low
3    Student4        90.0   9.100000     PG       0                High
4    Student5        72.0   7.000000   HOME       1              Medium
5    Student6        88.0   8.900000     PG       0                High
6    Student7        60.0   6.500000   HOME       0                 Low
7    Student8        82.0   8.000000     PG       1              Medium
8    Student9        75.0   7.200000   HOME       1              Medium
9   Student10        91.0   8.014583     PG       0                High
10  Student11        68.0   6.900000   HOME       0                 Low
11  Student12        87.0   8.700000     PG       1                High
12  Student13        77.0   7.800000   HOME       1              Medium
13  Student14        83.0   8.400000     PG       0              Medium
14  Student15        69.0   6.700000   HOME       1                 Low
15  Student16        92.0   9.500000     PG       0                High
16  Student17        74.0   8.014583   HOME       0              Medium
17  Student18        89.0   9.000000     PG       1                High
18  Student19        66.0   6.600000   HOME       1                 Low
19  Student20        80.0   7.900000     PG       0              Medium
20  Student21        71.0   7.000000   HOME       1              Medium
21  Student22        93.0   9.600000     PG       0                High
22  Student23        76.0   7.300000   HOME       0              Medium
23  Student24        86.0   8.800000     PG       1                High
24  Student25        64.0   6.400000   HOME       0                 Low
25  Student26        79.0   7.700000     PG       1              Medium
26  Student27        73.0   7.200000   HOME       1              Medium
27  Student28        94.0   9.700000     PG       0                High
28  Student29        67.0   6.800000   HOME       0                 Low
29  Student30        85.0   8.500000     PG       1              Medium
30  Student31        81.0   8.100000   HOME       1              Medium
31  Student32        84.0   8.300000     PG       0              Medium
32  Student33        70.0   7.000000   HOME       1                 Low
33  Student34        95.0   9.800000     PG       0                High
34  Student35        78.0   7.600000   HOME       0              Medium
35  Student36        90.0   9.200000     PG       1                High
36  Student37        62.0   6.300000   HOME       1                 Low
37  Student38        86.0   8.600000     PG       0                High
38  Student39        74.0   7.400000   HOME       1              Medium
39  Student40        96.0   9.900000     PG       0                High
40  Student41        69.0   6.900000   HOME       0                 Low
41  Student42        91.0   9.300000     PG       1                High
42  Student43        83.0   8.200000   HOME       0              Medium
43  Student44        88.0   8.900000     PG       1                High
44  Student45        72.0   7.100000   HOME       1              Medium
45  Student46        97.0  10.000000     PG       0                High
46  Student47        75.0   7.500000   HOME       0              Medium
47  Student48        92.0   9.400000     PG       1                High
48  Student49        68.0   6.800000   HOME       1                 Low
49  Student50        87.0   8.700000     PG       0                High

    GPA_MinMax  GPA_Zscore    GPA_DS  Department_CS  Department_Civil  \
0     0.513514    0.175235  0.000082          False             False
1     0.324324   -0.486325  0.000075          False             False
2     0.135135   -1.147885  0.000068          False             False
3     0.756757    1.025811  0.000091          False             False
4     0.189189   -0.958868  0.000070          False              True
5     0.702703    0.836794  0.000089           True             False
6     0.054054   -1.431410  0.000065          False             False
7     0.459459   -0.013782  0.000080          False             False
8     0.243243   -0.769851  0.000072          False             False
9     0.463401    0.000000  0.000080          False             False
10    0.162162   -1.053376  0.000069          False              True
11    0.648649    0.647777  0.000087           True             False
12    0.405405   -0.202800  0.000078          False             False
13    0.567568    0.364252  0.000084          False             False
14    0.108108   -1.242393  0.000067          False             False
15    0.864865    1.403845  0.000095          False             False
16    0.463401    0.000000  0.000080          False              True
17    0.729730    0.931303  0.000090           True             False
18    0.081081   -1.336902  0.000066          False             False
19    0.432432   -0.108291  0.000079          False             False
20    0.189189   -0.958868  0.000070          False             False
21    0.891892    1.498354  0.000096          False             False
22    0.270270   -0.675342  0.000073          False              True
23    0.675676    0.742286  0.000088           True             False
24    0.027027   -1.525919  0.000064          False             False
25    0.378378   -0.297308  0.000077          False             False
26    0.243243   -0.769851  0.000072          False             False
27    0.918919    1.592862  0.000097          False             False
28    0.135135   -1.147885  0.000068          False              True
29    0.594595    0.458760  0.000085           True             False
30    0.486486    0.080726  0.000081          False             False
31    0.540541    0.269743  0.000083          False             False
32    0.189189   -0.958868  0.000070          False             False
33    0.945946    1.687371  0.000098          False             False
34    0.351351   -0.391817  0.000076          False              True
35    0.783784    1.120320  0.000092           True             False
36    0.000000   -1.620427  0.000063          False             False
37    0.621622    0.553269  0.000086          False             False
38    0.297297   -0.580834  0.000074          False             False
39    0.972973    1.781879  0.000099          False             False
40    0.162162   -1.053376  0.000069          False              True
41    0.810811    1.214828  0.000093           True             False
42    0.513514    0.175235  0.000082          False             False
43    0.702703    0.836794  0.000089          False             False
44    0.216216   -0.864359  0.000071          False             False
45    1.000000    1.876388  0.000100          False             False
46    0.324324   -0.486325  0.000075          False              True
47    0.837838    1.309337  0.000094           True             False
48    0.135135   -1.147885  0.000068          False             False
49    0.648649    0.647777  0.000087          False             False

    Department_ENTC  Department_Mechanical  Department_Robotics
0             False                  False                False
1             False                  False                 True
2             False                   True                False
3              True                  False                False
4             False                  False                False
5             False                  False                False
6             False                  False                False
7             False                  False                 True
8             False                   True                False
9              True                  False                False
10            False                  False                False
11            False                  False                False
12            False                  False                False
13            False                  False                 True
14            False                   True                False
15             True                  False                False
16            False                  False                False
17            False                  False                False
18            False                  False                False
19            False                  False                 True
20            False                   True                False
21             True                  False                False
22            False                  False                False
23            False                  False                False
24            False                  False                False
25            False                  False                 True
26            False                   True                False
27             True                  False                False
28            False                  False                False
29            False                  False                False
30            False                  False                False
31            False                  False                 True
32            False                   True                False
33             True                  False                False
34            False                  False                False
35            False                  False                False
36            False                  False                False
37            False                  False                 True
38            False                   True                False
39             True                  False                False
40            False                  False                False
41            False                  False                False
42            False                  False                False
43            False                  False                 True
44            False                   True                False
45             True                  False                False
46            False                  False                False
47            False                  False                False
48            False                  False                False
49            False                  False                 True

Charts and Visual Encoding

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import LabelEncoder
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings

warnings.filterwarnings('ignore')

# Load data
df = pd.read_csv('/content/raw data students.csv')

# Basic data validation
print("Checking missing values...")
print(df.isnull().sum())
df = df.dropna(subset=['GPA', 'Attendance'])  # Drop rows with missing critical values
df = df[(df['GPA'] >= 0) & (df['GPA'] <= 10)]  # Ensure GPA is valid
df = df[(df['Attendance'] >= 0) & (df['Attendance'] <= 100)]  # Ensure Attendance is valid

# Set styling
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

print("Student Performance Analytics Dashboard")
print("Loading data...")

# Data preparation
dept_means = df.groupby('Department')['GPA'].mean().reset_index()
df['GPA_Category'] = pd.cut(df['GPA'], bins=[0,7,8,9,10], labels=['Poor','Average','Good','Excellent'])

# Encode Department for 3D plot
if 'Department_Enc' not in df.columns:
    le = LabelEncoder()
    df['Department_Enc'] = le.fit_transform(df['Department'])

# Main dashboard: 2x3 subplot
print("Creating main dashboard...")

fig = make_subplots(
    rows=2, cols=3,
    subplot_titles=('Gender Distribution', 'Department GPA Ranking', 'GPA Distribution',
                   'Attendance vs GPA', 'GPA by Living', 'Correlation Matrix'),
    specs=[[{"type": "bar"}, {"type": "bar"}, {"type": "histogram"}],
           [{"type": "scatter"}, {"type": "box"}, {"type": "heatmap"}]],
    horizontal_spacing=0.05, vertical_spacing=0.08
)

# 1. Gender distribution
gender_counts = df['Gender'].value_counts()
fig.add_trace(
    go.Bar(x=gender_counts.index, y=gender_counts.values,
           marker_color=['#FF6B6B', '#4ECDC4'],
           text=gender_counts.values, textposition='auto',
           name='Gender', hovertemplate='<b>%{x}</b><br>Count: %{y}<extra></extra>'),
    row=1, col=1
)

# 2. Department GPA - Dynamic colors
dept_colors = px.colors.qualitative.Set3
for i, dept in enumerate(dept_means['Department']):
    fig.add_trace(
        go.Bar(x=[dept], y=[dept_means.loc[i, 'GPA']],
               marker_color=dept_colors[i % len(dept_colors)],
               name=dept, hovertemplate='<b>%{customdata[0]}</b><br>Avg GPA: %{y:.2f}<extra></extra>',
               customdata=[[dept]]),
        row=1, col=2
    )

# 3. GPA Histogram
fig.add_trace(
    go.Histogram(x=df['GPA'], nbinsx=15, name='GPA',
                 marker_color='#A8E6CF', opacity=0.8,
                 hovertemplate='<b>GPA: %{x:.2f}</b><br>Count: %{y}<extra></extra>'),
    row=1, col=3
)

# 4. Scatter Plot with trendline
scatter_fig = px.scatter(df, x='Attendance', y='GPA', trendline="ols",
                         color='Gender', hover_data=['Student_ID'])
for trace in scatter_fig.data:
    fig.add_trace(trace, row=2, col=1)

# 5. Box Plot - GPA by Living
for living_type, color in zip(['Home', 'PG'], ['#FF9999', '#66B2FF']):
    fig.add_trace(
        go.Box(y=df[df['Living']==living_type]['GPA'], name=living_type,
               marker_color=color, hovertemplate=f'<b>{living_type}</b><br>%{{y:.2f}}<extra></extra>'),
        row=2, col=2
    )

# 6. Correlation Heatmap
corr_data = df[['Attendance', 'GPA']].corr()
fig.add_trace(
    go.Heatmap(z=corr_data.values, x=corr_data.columns, y=corr_data.columns,
               colorscale='RdBu_r', zmid=0, hoverongaps=False,
               hovertemplate='<b>%{x}</b> vs <b>%{y}</b><br>Correlation: %{z:.3f}<extra></extra>'),
    row=2, col=3
)

# Layout updates
fig.update_layout(
    title={'text': "Student Performance Analytics Dashboard", 'x': 0.5, 'xanchor': 'center',
           'font': {'size': 24, 'color': '#2C3E50', 'family': 'Arial Black'}},
    height=800, width=1400,
    plot_bgcolor='#F8F9FA',
    paper_bgcolor='#FFFFFF',
    font=dict(size=12, color='#2C3E50'),
    showlegend=True,
    hovermode='closest',
    updatemenus=[{
        "buttons": [
            {"method": "update", "label": "All Departments", "args": [{"visible": [True]*len(fig.data)}]},
            {"method": "update", "label": "Only GPA Charts", "args": [{"visible": [False, True, True, False, True, True]}]}
        ],
        "direction": "down", "showactive": True
    }]
)

fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='#E9ECEF')
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='#E9ECEF')

fig.show()

# 3D scatter plot
print("Creating 3D scatter plot...")
fig_3d = px.scatter_3d(df, x='Attendance', y='GPA', z='Department_Enc',
                      color='Gender', size='GPA', hover_name='Student_ID',
                      title="Attendance vs GPA vs Department",
                      color_discrete_map={'Male': '#FF6B6B', 'Female': '#4ECDC4'})
fig_3d.update_layout(height=700, width=1000)
fig_3d.show()

# Sunburst chart
print("Creating sunburst chart...")
sunburst_data = df.groupby(['Department', 'Living', 'Gender', 'GPA_Category']).size().reset_index(name='count')
sunburst_data = sunburst_data[sunburst_data['count'] > 0]
fig_sunburst = px.sunburst(sunburst_data, path=['Department', 'Living', 'Gender', 'GPA_Category'],
                          values='count',
                          title="Hierarchical Student Distribution",
                          color='count', color_continuous_scale='Viridis')
fig_sunburst.update_layout(height=700, width=800)
fig_sunburst.show()

# Gauge charts
print("Creating performance gauges...")
fig_gauge = make_subplots(1, 3, specs=[[{'type':'indicator'}, {'type':'indicator'}, {'type':'indicator'}]],
                         subplot_titles=('Overall GPA', 'Avg Attendance', 'Top Dept GPA'))

# Overall GPA gauge
fig_gauge.add_trace(
    go.Indicator(mode="gauge+number+delta",
                value=df['GPA'].mean(),
                title={'text': "Overall GPA"},
                delta={'reference': df['GPA'].median()},
                gauge={'axis': {'range': [0, 10]},
                      'bar': {'color': "#00B894"},
                      'threshold': {'line': {'color': "red", 'width': 4},
                                   'thickness': 0.75, 'value': df['GPA'].max()}}),
    row=1, col=1
)

# Attendance gauge
fig_gauge.add_trace(
    go.Indicator(mode="gauge+number",
                value=df['Attendance'].mean(),
                title={'text': "Avg Attendance"},
                gauge={'axis': {'range': [0, 100]},
                      'bar': {'color': "#0984e3"}}),
    row=1, col=2
)

# Top Department GPA gauge
top_dept = dept_means.loc[dept_means['GPA'].idxmax()]
fig_gauge.add_trace(
    go.Indicator(mode="gauge+number",
                value=top_dept['GPA'],
                title={'text': f"Top Dept: {top_dept['Department']}"},
                gauge={'axis': {'range': [0, 10]},
                      'bar': {'color': "#6C5CE7"}}),
    row=1, col=3
)

fig_gauge.update_layout(height=400, title_text="Key Performance Indicators")
fig_gauge.show()

print("\nDashboard complete.")
print("All charts are fully interactive.")

Checking missing values...
Student_ID    0
Department    0
Attendance    0
GPA           2
Living        0
Gender        0
dtype: int64
Student Performance Analytics Dashboard
Loading data...
Creating main dashboard...

Creating 3D scatter plot...

Creating sunburst chart...

Creating performance gauges...

Dashboard complete.
All charts are fully interactive.